import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ModalVideo from "@/components/ModalVideo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ammar Forte",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="light">
        <ModalVideo/>
        <div className="w-full flex justify-center items-center">
          <Navbar />
        </div>
        {children}
        <div className="w-full">
          <Footer />
        </div>
      </body>
    </html>
  );
}
